---
apiVersion: v1
kind: Pod
metadata:
  name: try-toy-plugins
  labels:
    app: try-toy-plugins
  annotations:
    ebiiim.com/maintainer.enabled: "true"
    ebiiim.com/maintainer.address: "John Smith <john@example.com>"
spec:
  schedulerName: toy-scheduler
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "infinity"
